/*********************************************************************************/
/********** THIS FILE IS GENERATED BY TOUCHGFX DESIGNER, DO NOT MODIFY ***********/
/*********************************************************************************/
#include <gui_generated/containers/NoteContainerBase.hpp>
#include <touchgfx/Color.hpp>

NoteContainerBase::NoteContainerBase()
{
    setWidth(50);
    setHeight(261);
    note.setPosition(2, 246, 45, 15);
    note.setOrigin(0.0f, 0.0f);
    note.setScale(1.0f, 1.0f);
    note.setAngle(0.0f);
    notePainter.setColor(touchgfx::Color::getColorFromRGB(255, 0, 0));
    note.setPainter(notePainter);
    const touchgfx::AbstractShape::ShapePoint<float> notePoints[4] = { { 0.0f, 0.0f }, { 0.0f, 15.0f }, { 50.0f, 15.0f }, { 50.0f, 0.0f } };
    note.setShape(notePoints);
    add(note);
}

NoteContainerBase::~NoteContainerBase()
{

}

void NoteContainerBase::initialize()
{

}

